var affirmations = [
  "You are not an executioner. You are the best goddamn bird lawyer in the world.",
  "Never let anyone’s resistance stop you from getting what you want.",
  "You’re a master of karate.",
  "I eat stickers all the time, dude.",
  "Science is a liar sometimes.",
  "If we’re gonna turn this company around, we gotta start cutting the crust off this shit sandwich!",
  "You are the golden god.",
  "You've got the stride of a gazelle.",
  "You're a man cheetah!",
  "We used to be losers, like all of you people.",
  "You have an exceptional number of bugs in your teeth. You’re gonna wanna rinse those out.",
  "You're the trash man!",
  "Any amount of cheese before a date is too much cheese.",
  "You do backflips every single day of your life",
  "Your nose was chiseled by the Gods themselves."
]
var mantras = [
  "Cat in the wall, eh?!",
  "I’m not gonna be buried in a grave. When I’m dead, just throw me in the trash. ",
  "If you’re dealt a bunch of lemons, you got to take those lemons, and stuff them down somebody’s throat until they see yellow.",
  "I haven’t even begun to peak. And when I do peak, you’ll know.",
  "I’m gonna stay right here, and I’m gonna wait for my minions to swarm me.",
  "Just get a job?! Why don’t I strap on my job helmet and squeeze down into a job cannon, and fire off into job land, where jobs grow on jobbies?!",
  "This bar runs on trash, dude. This bar is totally green that way.",
  "Well, I don't know how many years on this Earth I got left. I'm gonna get real weird with it.",
  "Smoke some cigarettes. The smoke will suffocate the bacteria in your stomach.",
  "Everybody’s dying, bitch.",
  "I’m not fat. I’m cultivating mass.",
  "Give it a rest. You’re not the Messiah. You don’t know dick about the Bible.",
  "Oh, you unzipped me! It’s all coming back! It’s all coming back; I hate you! It’s all coming back, you understand?! I DON’T LIKE IT! I DON’T LIKE TO THINK ABOUT IT!",
  "What is this word ‘spa?’ I feel like you’re starting to say a word and you’re not finishing it.",
  "Then, I’ll just regress, because I feel I made myself perfectly redundant.",
  "Wildcard, bitches! Yee-haw!"
]
