var affirmations = [
'I forgive myself and set myself free.',
'I believe I can be all that I want to be.',
'I am in the process of becoming the best version of myself.',
'I have the freedom & power to create the life I desire.',
'I choose to be kind to myself and love myself unconditionally.',
'My possibilities are endless.',
'I am worthy of my dreams.',
'I am enough.',
'I deserve to be healthy and feel good.',
'I am full of energy and vitality and my mind is calm and peaceful.',
'Every day I am getting healthier and stronger.',
'I honor my body by trusting the signals that it sends me.',
'I manifest perfect health by making smart choices.',
'Asking for help is a sign of self-respect and self-awareness.',
'Changing my mind is a strength, not a weakness.',
'Every decision I make is supported by my whole and inarguable experience.',
'I affirm and encourage others, as I do myself.',
'I alone hold the truth of who I am.',
'I am allowed to ask for what I want and what I need.',
'I am allowed to feel good.',
'I am capable of balancing ease and effort in my life.',
'I am complete as I am, others simply support me.',
'I am content and free from pain.',
'I am doing the work that works for me.',
'I am good and getting better.',
'I am growing and I am going at my own pace.',
'I am held and supported by those who love me.',
'I am in charge of how I feel and I choose to feel happy.',
'I am listening and open to the messages the universe has to offer today.',
'I am loved and worthy.',
'I am more than my circumstances dictate.',
'I am open to healing.',
'I am optimistic because today is a new day.',
'I am peaceful and whole.',
'I am proof enough of who I am and what I deserve.',
'I am responsible for myself, and I start there.',
'I am safe and surrounded by love and support.',
'I am still learning so it’s okay to make mistakes.',
'I am understood and my perspective is important.',
'I am valued and helpful.',
'I am well-rested and excited for the day.',
'I am worthy of investing in myself.',
'I belong here, and I deserve to take up space.',
];

var mantras = [
'In the beginning it is you, in the middle it is you and in the end it is you.',
'I love myself.',
'I am present now.',
'Inhale the future, exhale the past.',
'This too shall pass.',
'Yesterday is not today.',
'The only constant is change.',
'Onward and upward.',
'I am the sky, the rest is weather.',
'My mind is brilliant. My body is healthy. My spirit is tranquil.',
'I create my own path and walk it with joy.',
'My positive thoughts guide me to new heights.',
'I am conquering my fears and becoming stronger each day.',
'I will have a good day, because it’s my choice.',
'I am not afraid to be wrong.',
'My body is a temple. I keep my temple clean.',
'I hold the key to better health through eating better and exercise.',
'Good health is a practice, and I have patience.',
'I listen to my body and give it what it needs.',
'Every cell in my body is alive and beautiful.',
'My potential is limitless, and I choose where to spend my energy.',
'While I support others, I also ask for help when needed.',
'I surrender to the flow and have faith in the ultimate good.',
'I will speak with confidence and self-assurance.',
'My commitment to myself is unbreakable.',
];
